#!/bin/bash

sudo apt update -y

#downloading the requires dependencies
sudo apt-get install curl gnupg2 wget unzip -y

#adding the GPG key , Since Pritunl is not present bydefault in the Ubuntu
apt-key adv --keyserver hkp://keyserver.ubuntu.com --recv E162F504A20CDF15827F718D4B7C549A058F8B6B
apt-key adv --keyserver hkp://keyserver.ubuntu.com --recv 7568D9BB55FF9E5287D586017AE645C0CF8E292A


#adding the Pritunl Repository 
echo "deb http://repo.pritunl.com/stable/apt focal main" | tee /etc/apt/sources.list.d/pritunl.list

sudo apt-get update -y
sudo apt-get install pritunl -y

sudo systemctl start pritunl
sudo systemctl enable pritunl
	
	
#downloading and adding the MongoDB key
wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | sudo apt-key add -
#adding MongoDB repository
echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/5.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-5.0.list

sudo apt-get update

sudo apt-get install -y mongodb-org

sudo systemctl start mongod
sudo systemctl enable mongod
	
