#! /bin/bash

sudo apt update -y

#installing the dependencies required for pyenv 

echo Installing the required dependency 

sudo apt install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev \
libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python-openssl git

#clone the git repository 

echo Cloning the pyenv repository 
git clone https://github.com/pyenv/pyenv.git ~/.pyenv

#setting up the environment for pyenv in bashrc file 

echo 'export PATH="/home/ubuntu/.pyenv/bin:$PATH"' >> ~/.bashrc 
echo 'eval "$(pyenv init -)"' >> ~/.bashrc
echo 'eval "$(pyenv init --path)"' >> ~/.bashrc

#loading the terminal 



#setting up the error in installing python version 

echo 'deb http://security.ubuntu.com/ubuntu bionic-security main' | sudo tee -a /etc/apt/sources.list
sudo apt update && apt-cache policy libssl1.0-dev -y
sudo apt-get install libssl1.0-dev -y

exec "$SHELL" 
