#!/bin/bash

sudo apt update -y 
sudo apt upgrade -y

#checking pyenv is installed or not 
if[ $(which pyenv) == '/home/ubuntu/.pyenv/bin/pyenv']
then
        echo installing the pyenv-virtualenv
        git clone https://github.com/pyenv/pyenv-virtualenv.git $(pyenv root)/plugins/pyenv-virtualenv
        echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.bashrc
        
        echo pyenv-virtualenv has installed successfully
        exec "$SHELL"
else
        echo no pyenv is installed at location - /home/ubuntu/.pyenv/bin/pyenv
        echo install pyenv first then you can install pyenv-virtualenv
        echo you can install pyenv from https://github.com/its-vivek-goel/installation_on_ubuntu/blob/main/pyenv


